name: ns_eos
channels:
  - conda-forge
dependencies:
  - black=22.10.0
  - ipykernel=6.19.3
  - jupyter=1.0.0
  - matplotlib=3.6.2
  - nb_conda=2.2.1
  - numpy=1.23.5
  - pandas=1.5.2
  - pytest=7.2.0
  - pytest-cov=4.0.0
  - pytest-runner=6.0.0
  - python=3.10.8
  - scipy=1.9.3
